#!/bin/bash
echo '=== onyx (192.0.2.229) ==='
sshpass -p "REPLACE_WITH_YOUR_VM_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null onyx@192.0.2.229 "echo HERMES_SVC=$(systemctl is-active hermes.service); echo GW_SVC=$(systemctl is-active hermes-gateway.service); echo SOUL=$(test -f ~/.hermes/SOUL.md && echo yes); echo OCR=$(test -f ~/.hermes/skills/ocr/ocr.py && echo yes); echo MAILBOX=$(test -d ~/agent_mailbox && echo yes); echo VAULT=$(ls /sparksphear/ | head -1)"
echo '=== daisy (192.0.2.230) ==='
sshpass -p "REPLACE_WITH_YOUR_VM_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null daisy@192.0.2.230 "echo HERMES_SVC=$(systemctl is-active hermes.service); echo GW_SVC=$(systemctl is-active hermes-gateway.service); echo SOUL=$(test -f ~/.hermes/SOUL.md && echo yes); echo OCR=$(test -f ~/.hermes/skills/ocr/ocr.py && echo yes); echo MAILBOX=$(test -d ~/agent_mailbox && echo yes); echo VAULT=$(ls /sparksphear/ | head -1)"
echo '=== eissa (192.0.2.231) ==='
sshpass -p "REPLACE_WITH_YOUR_VM_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null eissa@192.0.2.231 "echo HERMES_SVC=$(systemctl is-active hermes.service); echo GW_SVC=$(systemctl is-active hermes-gateway.service); echo SOUL=$(test -f ~/.hermes/SOUL.md && echo yes); echo OCR=$(test -f ~/.hermes/skills/ocr/ocr.py && echo yes); echo MAILBOX=$(test -d ~/agent_mailbox && echo yes); echo VAULT=$(ls /sparksphear/ | head -1)"
echo '=== shima (192.0.2.232) ==='
sshpass -p "REPLACE_WITH_YOUR_VM_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null shima@192.0.2.232 "echo HERMES_SVC=$(systemctl is-active hermes.service); echo GW_SVC=$(systemctl is-active hermes-gateway.service); echo SOUL=$(test -f ~/.hermes/SOUL.md && echo yes); echo OCR=$(test -f ~/.hermes/skills/ocr/ocr.py && echo yes); echo MAILBOX=$(test -d ~/agent_mailbox && echo yes); echo VAULT=$(ls /sparksphear/ | head -1)"
echo '=== travis (192.0.2.233) ==='
sshpass -p "REPLACE_WITH_YOUR_VM_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null travis@192.0.2.233 "echo HERMES_SVC=$(systemctl is-active hermes.service); echo GW_SVC=$(systemctl is-active hermes-gateway.service); echo SOUL=$(test -f ~/.hermes/SOUL.md && echo yes); echo OCR=$(test -f ~/.hermes/skills/ocr/ocr.py && echo yes); echo MAILBOX=$(test -d ~/agent_mailbox && echo yes); echo VAULT=$(ls /sparksphear/ | head -1)"
